#!/bin/sh -

echo 1>&2 "pkg-upgrade invoked with arguments \"$*\"."

case $2 in

PRE-UPGRADE)
    ;;

POST-UPGRADE)
    ;;

*)
    echo "No clue what this script is meant to do when invoked with arguments \"$*\"."
    #exit 1
    ;;

esac
