#!/bin/sh -

case $2 in

DEINSTALL)
    if cmp -s /usr/local/etc/rpki.conf.sample /usr/local/etc/rpki.conf; then
	rm -f /usr/local/etc/rpki.conf
    fi
    ;;

POST-DEINSTALL)
    ;;

*)
    echo "No clue what this script is meant to do when invoked with arguments \"$*\".  Punting."
    exit 1
    ;;

esac
