#!/usr/bin/env python

import os

# django-admin seems to have problems creating the superuser account when
# $LANG is unset or is set to something totally incompatible with UTF-8.

if os.environ.get("LANG") in (None, "", "C"):
    os.environ["LANG"] = "en_US.UTF-8"

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "rpki.django_settings.gui")

from django.core.management import execute_from_command_line

execute_from_command_line()
