#!/bin/sh -
#
# $Id$
#
. /etc/rc.common

name="rcynic"
start_cmd="rcynic_start"
stop_cmd="rcynic_stop"

: ${rcynic_jaildir="/var/rcynic"}
: ${rcynic_user="rcynic"}
: ${rcynic_group="rcynic"}

StartService()
{
	/bin/test -d "${rcynic_jaildir}" || /bin/mkdir "${rcynic_jaildir}"
	/sbin/umount "${rcynic_jaildir}/dev" 2>/dev/null

	/usr/sbin/mtree -deU -p "${rcynic_jaildir}" <<EOF

		/set type=dir uname=root gname=wheel mode=0555
		.
			bin
			..
			dev
			..
			etc
				trust-anchors
				..
			..
			usr
				lib
					system
					..
				..
			..
			var
				run
				..
			..
			data	uname=${rcynic_user} gname=${rcynic_group} mode=0755
			..
		..
EOF

	/bin/chmod -R a-w "${rcynic_jaildir}/bin" "${rcynic_jaildir}/etc"
	/usr/sbin/chown -R root:wheel "${rcynic_jaildir}/bin" "${rcynic_jaildir}/etc"

	if /bin/test -f "${rcynic_jaildir}/etc/rsa_key"; then
		/bin/chmod 400 "${rcynic_jaildir}/etc/rsa_key"
		/usr/sbin/chown "${rcynic_user}" "${rcynic_jaildir}/etc/rsa_key"
	fi

	if ! /sbin/mount_devfs devfs "${rcynic_jaildir}/dev"; then
		echo "Mounting devfs on ${rcynic_jaildir}/dev failed..."
		exit 1
	fi

	for i in /etc/localtime /etc/resolv.conf; do
		j="${rcynic_jaildir}${i}"
		if /bin/test -r "$i" && ! /usr/bin/cmp -s "$i" "$j"; then
			/usr/bin/install -m 444 -o root -g wheel -p "$i" "$j"
		fi
	done

	/bin/ln -f /var/run/mDNSResponder "${rcynic_jaildir}/var/run/mDNSResponder"
}

StopService()
{
	/sbin/umount "${rcynic_jaildir}/dev" 2>/dev/null
}

RestartService()
{
	StartService
}

RunService "$1"
