# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import rpki.gui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_min', rpki.gui.models.IPAddressField(db_index=True)),
                ('prefix_max', rpki.gui.models.IPAddressField(db_index=True)),
                ('asn', models.PositiveIntegerField(help_text=b'origin AS')),
            ],
            options={
                'ordering': ('prefix_min', '-prefix_max'),
            },
        ),
        migrations.CreateModel(
            name='RouteOriginV6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_min', rpki.gui.models.IPAddressField(db_index=True)),
                ('prefix_max', rpki.gui.models.IPAddressField(db_index=True)),
                ('asn', models.PositiveIntegerField(help_text=b'origin AS')),
            ],
            options={
                'ordering': ('prefix_min', '-prefix_max'),
            },
        ),
    ]
