# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import rpki.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpkidb', '0007_auto_20151020_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsc',
            name='pkcs10_request',
            field=rpki.fields.PKCS10Field(),
        ),
        migrations.AlterField(
            model_name='bsc',
            name='private_key_id',
            field=rpki.fields.RSAPrivateKeyField(),
        ),
        migrations.AlterField(
            model_name='bsc',
            name='signing_cert',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='bsc',
            name='signing_cert_crl',
            field=rpki.fields.CRLField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='latest_ca_cert',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='latest_crl',
            field=rpki.fields.CRLField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='latest_manifest',
            field=rpki.fields.ManifestField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='latest_manifest_cert',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='manifest_private_key_id',
            field=rpki.fields.RSAPrivateKeyField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='manifest_public_key',
            field=rpki.fields.PublicKeyField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='private_key_id',
            field=rpki.fields.RSAPrivateKeyField(null=True),
        ),
        migrations.AlterField(
            model_name='cadetail',
            name='public_key',
            field=rpki.fields.PublicKeyField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='bpki_cert',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='bpki_glue',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='childcert',
            name='cert',
            field=rpki.fields.CertificateField(),
        ),
        migrations.AlterField(
            model_name='eecertificate',
            name='cert',
            field=rpki.fields.CertificateField(),
        ),
        migrations.AlterField(
            model_name='ghostbuster',
            name='cert',
            field=rpki.fields.CertificateField(),
        ),
        migrations.AlterField(
            model_name='ghostbuster',
            name='ghostbuster',
            field=rpki.fields.GhostbusterField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='bpki_cert',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='bpki_glue',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='bpki_cert',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='bpki_glue',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='roa',
            name='cert',
            field=rpki.fields.CertificateField(),
        ),
        migrations.AlterField(
            model_name='roa',
            name='roa',
            field=rpki.fields.ROAField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='bpki_cert',
            field=rpki.fields.CertificateField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='bpki_glue',
            field=rpki.fields.CertificateField(null=True),
        ),
    ]
