#!/usr/bin/env python

# $Id$
#
# Copyright (C) 2014  Dragon Research Labs ("DRL")
# Portions copyright (C) 2010-2013  Internet Systems Consortium ("ISC")
# 
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notices and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND DRL AND ISC DISCLAIM ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL DRL OR
# ISC BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA
# OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

"""
Back up data from SQL databases, looking at config file to figure out
which databases and what credentials to use with them.

For the moment, this just writes all the SQL to stdout.
"""

import subprocess
import os
import argparse
import sys
import time
import rpki.config

os.environ["TZ"] = "UTC"
time.tzset()

parser = argparse.ArgumentParser(description = __doc__)
parser.add_argument("-c", "--config",
                    help = "override default location of configuration file")
args = parser.parse_args()

cfg = rpki.config.parser(args.config, "myrpki")

def dump(section):
  subprocess.check_call(
    ("mysqldump", "--add-drop-database",
     "-u",  cfg.get("sql-username", section = section),
     "-p" + cfg.get("sql-password", section = section),
     "-B",  cfg.get("sql-database", section = section)))

if cfg.getboolean("start_rpkid", False):
  dump("irdbd")

if cfg.getboolean("start_irdbd", False):
  dump("rpkid")

if cfg.getboolean("start_pubd",  False):
  dump("pubd")
