-- $Id$

-- Copyright (C) 2009  Internet Systems Consortium ("ISC")
--
-- Permission to use, copy, modify, and distribute this software for any
-- purpose with or without fee is hereby granted, provided that the above
-- copyright notice and this permission notice appear in all copies.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH
-- REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
-- AND FITNESS.  IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT,
-- INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
-- LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
-- OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
-- PERFORMANCE OF THIS SOFTWARE.

-- Clean up databases left behind by testbed.py et al.

DROP DATABASE IF EXISTS irdb0;
DROP DATABASE IF EXISTS irdb1;
DROP DATABASE IF EXISTS irdb2;
DROP DATABASE IF EXISTS irdb3;
DROP DATABASE IF EXISTS irdb4;
DROP DATABASE IF EXISTS irdb5;
DROP DATABASE IF EXISTS irdb6;
DROP DATABASE IF EXISTS irdb7;
DROP DATABASE IF EXISTS irdb8;
DROP DATABASE IF EXISTS irdb9;
DROP DATABASE IF EXISTS irdb10;
DROP DATABASE IF EXISTS irdb11;
DROP DATABASE IF EXISTS rpki0;
DROP DATABASE IF EXISTS rpki1;
DROP DATABASE IF EXISTS rpki2;
DROP DATABASE IF EXISTS rpki3;
DROP DATABASE IF EXISTS rpki4;
DROP DATABASE IF EXISTS rpki5;
DROP DATABASE IF EXISTS rpki6;
DROP DATABASE IF EXISTS rpki7;
DROP DATABASE IF EXISTS rpki8;
DROP DATABASE IF EXISTS rpki9;
DROP DATABASE IF EXISTS rpki10;
DROP DATABASE IF EXISTS rpki11;
DROP DATABASE IF EXISTS pubd0;
DROP DATABASE IF EXISTS pubd1;
DROP DATABASE IF EXISTS pubd2;
DROP DATABASE IF EXISTS pubd3;
DROP DATABASE IF EXISTS pubd4;
DROP DATABASE IF EXISTS pubd5;
DROP DATABASE IF EXISTS pubd6;
DROP DATABASE IF EXISTS pubd7;
DROP DATABASE IF EXISTS pubd8;
DROP DATABASE IF EXISTS pubd9;
DROP DATABASE IF EXISTS pubd10;
DROP DATABASE IF EXISTS pubd11;
